### PR TITLE
Corrected a bug that lead to a crash when importing BD Accuri files.

### PR DESCRIPTION
**Pull request by pintomollo**
It appears that the bug was due to a combination of renaming channels and the deletion of extra bits during import. Indexing on the renamed channel in the data structure was necessary. Only import_op.py was modified, in the apply function. I simply stored the new_channel and reused it to index the data DataFrame during extra bits masking.

I've run the two test_import and they didn't raise any error. I've run the GUI and was able to import the BD Accuri file that is provided in the instruments folder. I was also able to load my own Accuri data using the whole GUI.

Hope that helps.

### CODE REVIEW

**Comment by pintomollo** [comment]
I believe that it is a solution to the issue #242

**Comment by pauloxisto** [comment]
I will give it a try again in the following week and will return with a feedback, thanks!

**Comment by bpteague** [comment]
I'm sorry that I've let this languish! The fix seems straightforward enough. Could you please reply with a sample FCS file that shows the bug?

**Comment by bpteague** [comment]
You're right that this was a bad interaction between the channel renaming and some of the Accuri-specific code. Fixed in the latest release.

**Pull request closed without merging**
